# Generated by Django 3.2 on 2021-12-16 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0056_auto_20211216_2152'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Наличностью'), ('electronic', 'Электронно')], db_index=True, default=('cash', 'Наличностью'), max_length=20, verbose_name='Способ оплаты'),
        ),
    ]
