# Generated by Django 3.2 on 2021-09-28 14:33

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0037_auto_20210125_1833'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=20, verbose_name='имя')),
                ('lastname', models.CharField(max_length=20, verbose_name='фамилия')),
                ('telephone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None, verbose_name='телефон')),
                ('address', models.CharField(max_length=200, verbose_name='адрес')),
                ('products', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='foodcartapp.product', verbose_name='продукты')),
            ],
        ),
    ]
