# Generated by Django 3.2 on 2021-11-17 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0046_auto_20211103_1714'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='telephone',
            new_name='phonenumber',
        ),
    ]
