# Generated by Django 3.2 on 2021-12-09 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0049_auto_20211209_0718'),
    ]

    operations = [
    ]
