# Generated by Django 3.2 on 2022-01-13 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0060_auto_20220113_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Наличностью'), ('electronic', 'Электронно'), ('not_specified', 'Не указано')], db_index=True, default='not_specified', max_length=20, verbose_name='Способ оплаты'),
        ),
    ]
