# Generated by Django 3.2 on 2022-01-03 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=100, verbose_name='адрес')),
                ('latitude', models.FloatField(verbose_name='широта')),
                ('longitude', models.FloatField(verbose_name='долгота')),
                ('date', models.DateField(verbose_name='дата запроса')),
            ],
            options={
                'verbose_name': 'геолокация',
                'verbose_name_plural': 'геолокации',
            },
        ),
    ]
