# Generated by Django 3.2 on 2022-01-04 02:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('geolocations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='date',
        ),
        migrations.AddField(
            model_name='location',
            name='created_on',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='дата запроса'),
        ),
        migrations.AlterField(
            model_name='location',
            name='address',
            field=models.CharField(max_length=100, verbose_name='адрес'),
        ),
    ]
