# Generated by Django 3.2 on 2022-01-13 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geolocations', '0003_alter_location_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='latitude',
            field=models.FloatField(blank=True, verbose_name='широта'),
        ),
        migrations.AlterField(
            model_name='location',
            name='longitude',
            field=models.FloatField(blank=True, verbose_name='долгота'),
        ),
    ]
