# Generated by Django 3.2 on 2022-02-01 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geolocations', '0004_auto_20220113_2233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='latitude',
            field=models.FloatField(blank=True, null=True, verbose_name='широта'),
        ),
        migrations.AlterField(
            model_name='location',
            name='longitude',
            field=models.FloatField(blank=True, null=True, verbose_name='долгота'),
        ),
    ]
