# Generated by Django 3.2 on 2022-07-16 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geolocations', '0005_auto_20220201_1908'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={'verbose_name': 'geolocation', 'verbose_name_plural': 'geolocations'},
        ),
    ]
